---
# yaml-language-server:
# $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Séances des Cassiopéens
site_url: https://isparnid/github.io/cassiopeens
repo_url: https://github.com/isparnid/cassiopeens
site_author : Membres du groupe de traduction FOTCM
repo_name: GitHub
use_directory_urls: true
extra:
  consent:
    title: Cookie autorisation
    actions:
      - accept
      - reject
      - manage
    description: >-
      Nous utilisons les cookies pour faciliter la collecte des données
      relatives aux visites de notre Site, et dans certains cas pour fournir
      un contenu plus pertinent. Un cookie ne peut pas lire les données de votre
      disque dur ni les fichiers de cookie créés par d’autres sites.
      En donnant votre consentement, vous nous aidez à améliorer
      notre documentation.

copyright: Copyright &copy 2025 Membres du groupe de traduction FOTCM
validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.tilde
  - toc:
      permalink: ⚓︎

theme:
  language: fr
  name: material
  custom_dir: overrides
  favicon: assets/favicon.jpg
  logo: assets/logo.png
  features:
    - content.footnote.tooltips
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # - navigation.sections
    - navigation.path
    # - navigation.prune
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  # - optimize
  - minify:
      minify_html: true
  - document-dates:
     position: top
     type: date
     exclude:
       - overrides/*
       - dev/*
       - .*
     date_format: '%d-%m-%Y'
     time_format: '%H:%M:%S'
     show_created: true
     show_updated: true
     show_author: true
